language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install wheel
script:
  - pytest
before_deploy:
  - export PACKAGE_VERSION="$(git describe)"
deploy:
  provider: pypi
  user: arnoldosmium
  password:
    secure: d3aUH/z+7y6Cx0qheRh2/RWlbDXPAO6v/LvJATim2zJ8ystZ41bpYHxLhLWF7sa7RSqcMV0m4JUHXTVoHlqG2/K74ocEjEIxYwUVXU0wykE4SbrdxbWSPgBOXdZQDD1gi9UW7QXRjgq1XNlcZgPjhtC0TUxWZ3rNl7siD8ZT2zyWFMu7I9LqNJZqNxZXF+QtOURn2J+wZcv0heN6x7Llg4eu61WS1GNM3RLESEURPwSycTTERaax/hr+CGJJCnvM2mK3+pg/5ILKnMz6MXm5VDhg3Hfe/DbGjM/tqCO8idnc3Hj3aX8S9VeA55xM7dFWlvaMa30udJBVkrBmhy5MY94DnfKpMT7qYnwLiTjCYL4yuAiVL9eqBBwDEfFK7Cr8oOG7+TarMaLQmWNAIcvRUsa46ITN/0nXbieZ4UIRiykKkQDZu3zcrM4DbCzgWpKDepCcbWaoklktlFzNTk40w97f/dqUC8yNjeuvSP8KyC//mV4p/+4eITkiJTBYFifSNA79bnUkoFhLSCxbeGrA1SeecI/sGdWQgFoHA6nEyDYk2PpHB7Aya0WscJMHsJ+80xVPMJHhdMKNw55ZWInYEwH0HfuG3wED7TXcmHUWGjlXt/FTQ34pLrx5fYkKT4MHguZHIdMlZF/00Qy7Z73c+gMBG496wekdtNCxXV21x08=
  distributions: bdist_wheel
  on:
    python: 3.6
    tags: true
